import {cookies} from 'next/headers';
import {hash} from './security';
export {hash,equal} from './security';
import {z} from 'zod';
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function fail(error:unknown){if(error instanceof HttpError)return Response.json({error:error.message},{status:error.status});if(error instanceof z.ZodError)return Response.json({error:'Revise os campos informados e tente novamente.'},{status:400});console.error('Casa Aura request failed',error instanceof Error?error.name:'UnknownError');return Response.json({error:'Não foi possível concluir. Tente novamente em instantes.'},{status:503})}
export async function jsonBody(request:Request){if(Number(request.headers.get('content-length')||0)>24000)throw new HttpError(413,'Solicitação muito grande.');const text=await request.text();if(text.length>24000)throw new HttpError(413,'Solicitação muito grande.');try{return JSON.parse(text)}catch{throw new HttpError(400,'Dados inválidos.')}}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');const expected=process.env.NEXT_PUBLIC_SITE_URL||new URL(request.url).origin;if(!origin||new URL(origin).origin!==new URL(expected).origin)throw new HttpError(403,'Origem da solicitação inválida.')}
export async function db<T=unknown>(path:string,init:RequestInit={}):Promise<T>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new HttpError(503,'A área da marca estará disponível após a configuração.');const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,'Content-Type':'application/json',Prefer:'return=representation',...init.headers},cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new HttpError(r.status===409?409:503,r.status===409?'Este registro já existe.':'Não foi possível salvar ou consultar os dados.');const text=await r.text();return (text?JSON.parse(text):null) as T;}
export async function requireAdmin(){const token=(await cookies()).get('aura-admin')?.value;if(!token)throw new HttpError(401,'Entre na área da marca.');const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY;if(!url||!key)throw new HttpError(503,'Administração indisponível.');const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`},cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw new HttpError(401,'Sua sessão expirou. Entre novamente.');const user=await r.json();const admins=await db<{user_id:string}[]>(`app_admins?user_id=eq.${encodeURIComponent(user.id)}&select=user_id`);if(!admins.length)throw new HttpError(403,'Acesso restrito à equipe da marca.');return user.id as string;}
export async function rateLimit(request:Request,scope:string,limit=15){const ip=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';const key=hash(`${scope}:${ip}:${process.env.RATE_LIMIT_SALT||process.env.SUPABASE_SERVICE_ROLE_KEY}`);const allowed=await db<boolean>('rpc/take_rate_limit',{method:'POST',body:JSON.stringify({p_key:key,p_limit:limit})});if(!allowed)throw new HttpError(429,'Muitas tentativas. Aguarde um minuto e tente novamente.');}
