import {z} from 'zod';
import {checkoutSchema} from '@/lib/validation';
import {sameOrigin,jsonBody,fail,HttpError,db,hash,equal,rateLimit} from '@/lib/server';
import {shopReady} from '@/lib/catalog';
import {getSiteSettings} from '@/lib/settings';
import {priceCart,quoteShipping} from '@/lib/shipping';
import {mercado} from '@/lib/payments';
import {createHmac} from 'node:crypto';
export const dynamic='force-dynamic';
type Order={id:string;payload_hash:string;payment_result:Record<string,string>|null;status:string;method:string;payment_token_hash:string;total_cents:number};
function orderToken(id:string){return createHmac('sha256',process.env.ORDER_TOKEN_SECRET||process.env.MERCADO_PAGO_WEBHOOK_SECRET!).update(`order:${id}`).digest('hex')}
export async function POST(request:Request){try{sameOrigin(request);if(!shopReady())throw new HttpError(503,'As vendas ainda não estão abertas. Nenhuma cobrança foi realizada.');const settings=await getSiteSettings();const pixDiscount=Math.max(0,Math.min(100,Number(settings.pix_discount_percent)||0));const pixTotal=(cents:number)=>Math.round(cents*(1-pixDiscount/100));await rateLimit(request,'checkout',10);const id=z.string().uuid().parse(request.headers.get('idempotency-key'));const data=checkoutSchema.parse(await jsonBody(request));const payloadHash=hash(JSON.stringify(data));const token=orderToken(id);let [order]=await db<Order[]>(`orders?id=eq.${id}`);if(order&&order.payload_hash!==payloadHash)throw new HttpError(409,'Revise a compra antes de tentar novamente.');if(order?.payment_result?.expires_at&&Date.now()>new Date(order.payment_result.expires_at).getTime())throw new HttpError(409,'Este pagamento expirou. Volte ao checkout para iniciar uma nova tentativa.');if(order?.payment_result)return Response.json({...order.payment_result,order_id:id,token});if(order&&order.status!=='pending')throw new HttpError(409,'Este pedido já foi processado. Confira seu e-mail.');
 if(!order){const lines=await priceCart(data.items);const options=await quoteShipping(data.cep,data.items);const delivery=options.find(o=>o.id===data.shipping_id);if(!delivery)throw new HttpError(409,'O frete mudou. Consulte novamente antes de pagar.');const subtotal=lines.reduce((s,i)=>s+i.product.price_cents*i.quantity,0);const total=(data.method==='pix'?pixTotal(subtotal):subtotal)+delivery.price_cents;if(total!==data.expected_total)throw new HttpError(409,'O preço ou frete mudou. Revise os valores e consulte a entrega novamente.');const draft={id,payload_hash:payloadHash,payment_token_hash:hash(token),customer_name:data.customer.name,email:data.customer.email,address:{...data.address,cep:data.cep},method:data.method,items:lines.map(i=>({id:i.id,name:i.product.name,quantity:i.quantity,unit_price_cents:i.product.price_cents})),subtotal_cents:subtotal,discount_cents:data.method==='pix'?subtotal-pixTotal(subtotal):0,shipping_cents:delivery.price_cents,shipping_name:delivery.name,total_cents:total,status:'pending'};try{[order]=await db<Order[]>('orders',{method:'POST',body:JSON.stringify(draft)})}catch(e){if(!(e instanceof HttpError)||e.status!==409)throw e;[order]=await db<Order[]>(`orders?id=eq.${id}`);if(!order||order.payload_hash!==payloadHash)throw new HttpError(409,'Pedido em atualização. Tente novamente.')}}
 const claimed=await db<boolean>('rpc/claim_payment',{method:'POST',body:JSON.stringify({p_id:id})});if(!claimed)throw new HttpError(409,'Seu pagamento está sendo preparado. Aguarde alguns instantes antes de tentar novamente.');const base=process.env.NEXT_PUBLIC_SITE_URL!.replace(/\/$/,'');if(!base.startsWith('https://'))throw new HttpError(503,'A loja ainda está sendo preparada.');let result:Record<string,string>;try{if(data.method==='pix'){const pay=await mercado('/v1/payments',{method:'POST',headers:{'X-Idempotency-Key':id},body:JSON.stringify({transaction_amount:order.total_cents/100,description:`Casa Aura · Pedido ${id.slice(0,8)}`,payment_method_id:'pix',external_reference:id,notification_url:`${base}/api/webhooks/mercadopago`,date_of_expiration:new Date(Date.now()+30*60000).toISOString(),payer:{email:data.customer.email,first_name:data.customer.name.split(' ')[0],last_name:data.customer.name.split(' ').slice(1).join(' '),identification:{type:'CPF',number:data.customer.cpf}}})});const tx=pay.point_of_interaction?.transaction_data;if(!tx?.qr_code||!tx?.qr_code_base64)throw new HttpError(503,'Não foi possível gerar o Pix. Tente novamente.');result={qr_code:tx.qr_code,qr_code_base64:tx.qr_code_base64,expires_at:pay.date_of_expiration||new Date(Date.now()+30*60000).toISOString()};await db(`orders?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({payment_id:String(pay.id),payment_result:result,payment_claimed_at:null})})}else{const pref=await mercado('/checkout/preferences',{method:'POST',headers:{'X-Idempotency-Key':id},body:JSON.stringify({items:[{id,title:`Casa Aura · Pedido ${id.slice(0,8)}`,quantity:1,currency_id:'BRL',unit_price:order.total_cents/100}],payer:{email:data.customer.email},external_reference:id,notification_url:`${base}/api/webhooks/mercadopago`,back_urls:{success:`${base}/checkout/retorno`,pending:`${base}/checkout/retorno`,failure:`${base}/checkout/retorno`},auto_return:'approved',expires:true,expiration_date_to:new Date(Date.now()+30*60000).toISOString(),payment_methods:{installments:Math.max(1,Math.min(24,Number(settings.max_installments)||12)),excluded_payment_types:[{id:'ticket'},{id:'bank_transfer'},{id:'atm'},{id:'debit_card'},{id:'prepaid_card'}]}})});const redirect=process.env.MERCADO_PAGO_SANDBOX==='true'?pref.sandbox_init_point:pref.init_point;if(typeof redirect!=='string'||!/^https:\/\/(www\.|sandbox\.)?mercadopago\.com\.br\//.test(redirect))throw new HttpError(503,'O link de pagamento não está disponível.');result={redirect,expires_at:new Date(Date.now()+30*60000).toISOString()};await db(`orders?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({preference_id:String(pref.id),payment_result:result,payment_claimed_at:null})})}}catch(e){await db(`orders?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({payment_claimed_at:null})});throw e}return Response.json({...result,order_id:id,token});}catch(e){return fail(e)}}
export async function GET(request:Request){try{const url=new URL(request.url);const id=z.string().uuid().parse(url.searchParams.get('id'));const token=z.string().regex(/^[a-f0-9]{64}$/).parse(url.searchParams.get('token'));const [order]=await db<Order[]>(`orders?id=eq.${id}&select=id,status,payment_token_hash`);if(!order||!equal(hash(token),order.payment_token_hash))throw new HttpError(404,'Pedido não encontrado.');return Response.json({status:order.status},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
