'use client';
import Link from 'next/link';
import {Plus,ArrowRight,Minus,ChevronRight,Truck} from 'lucide-react';
import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {useCart} from './provider';
import {money,pixPrice,type Product} from '@/lib/catalog';
import type {ShippingOption,CartLine} from '@/lib/types';
export function Breadcrumb({current}:{current:string}){return <div className="breadcrumb"><Link href="/">Início</Link><ChevronRight/><Link href="/loja">Loja</Link><ChevronRight/><span>{current}</span></div>}
export function ProductCard({product:p,index=0}:{product:Product;index?:number}){const{add}=useCart();return <article className="product-card"><div className="product-image"><Link href={`/produto/${p.slug}`} tabIndex={-1} aria-hidden="true"><img src={p.images[0]} alt={p.name} loading="lazy" decoding="async" width={512} height={640}/></Link>{index===0&&<span className="product-tag">O encanto dos detalhes</span>}<button className="add-small" disabled={!p.stock} aria-label={`Adicionar ${p.name} à sacola`} onClick={()=>add(p.id)}><Plus/></button></div><div className="product-info"><p className="eyebrow">{p.category==='gesso'?'Gesso artesanal':'Têxtil artesanal'} <span aria-hidden="true">·</span> {p.color}</p><h3><Link href={`/produto/${p.slug}`}>{p.name}</Link></h3><p className="price">{money(p.price_cents)}</p><p className="pix">ou {money(pixPrice(p.price_cents))} no Pix</p></div></article>}
export function Catalog({initial='todas'}:{initial?:string}){const{products,demo}=useCart();const[category,setCategory]=useState(['gesso','textil'].includes(initial)?initial:'todas'),[sort,setSort]=useState('curadoria');const filtered=products.filter(p=>category==='todas'||p.category===category).sort((a,b)=>sort==='menor'?a.price_cents-b.price_cents:sort==='maior'?b.price_cents-a.price_cents:sort==='nome'?a.name.localeCompare(b.name):0);return <><div className="catalog-controls"><Tabs value={category} onValueChange={setCategory}><TabsList aria-label="Filtrar por categoria"><TabsTrigger value="todas">Todas as peças</TabsTrigger><TabsTrigger value="gesso">Gesso</TabsTrigger><TabsTrigger value="textil">Têxtil</TabsTrigger></TabsList></Tabs><div className="filter-right"><span className="small muted" aria-live="polite">{filtered.length} peças</span><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Ordenar peças" style={{border:0,boxShadow:'none',fontSize:14}}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="curadoria">Nossa curadoria</SelectItem><SelectItem value="menor">Menor preço</SelectItem><SelectItem value="maior">Maior preço</SelectItem><SelectItem value="nome">Nome A–Z</SelectItem></SelectContent></Select></div></div>{filtered.length?<div className="product-grid catalog-grid">{filtered.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div>:<div className="empty-state"><h2>Novas peças a caminho.</h2><p>Volte em breve para descobrir a coleção.</p></div>}{demo&&<p className="demo-note" style={{paddingBottom:30}}>Coleção demonstrativa. Imagens ilustrativas e preços de exemplo; vendas ainda não disponíveis.</p>}</>}
export function Quantity({value,onChange,max=20}:{value:number;onChange:(v:number)=>void;max?:number}){return <div className="quantity"><button type="button" aria-label="Diminuir quantidade" disabled={value<=1} onClick={()=>onChange(value-1)}><Minus/></button><span aria-live="polite">{value}</span><button type="button" aria-label="Aumentar quantidade" disabled={value>=max} onClick={()=>onChange(value+1)}><Plus/></button></div>}
export function ShippingCalculator({items,onSelect,onInvalidate}:{items:CartLine[];onSelect?:(option:ShippingOption,cep:string)=>void;onInvalidate?:()=>void}){const[cep,setCep]=useState(''),[busy,setBusy]=useState(false),[options,setOptions]=useState<ShippingOption[]>([]),[error,setError]=useState('');async function calculate(e:React.FormEvent){e.preventDefault();setError('');setOptions([]);setBusy(true);try{const r=await fetch('/api/frete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cep:cep.replace(/\D/g,''),items})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOptions(d.options);if(d.options.length&&onSelect)onSelect(d.options[0],cep.replace(/\D/g,''));}catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar o frete.')}finally{setBusy(false)}}return <div className="shipping"><h3><Truck/>Um novo destino para sua peça</h3><form className="shipping-row" onSubmit={calculate}><input className="field" aria-label="CEP de entrega" inputMode="numeric" autoComplete="postal-code" placeholder="00000-000" required pattern="\d{5}-?\d{3}" maxLength={9} value={cep} onChange={e=>{const digits=e.target.value.replace(/\D/g,'').slice(0,8);setCep(digits.replace(/(\d{5})(\d)/,'$1-$2'));setOptions([]);setError('');onInvalidate?.()}}/><button className="button button-outline" disabled={busy}>{busy?'Consultando…':'Calcular frete'}</button></form>{error&&<p className="shipping-result" role="status">{error}</p>}{options.map(o=><div key={o.id} className="shipping-result">{onSelect?<label style={{display:'flex',gap:10}}><input type="radio" name="shipping" defaultChecked={o===options[0]} onChange={()=>onSelect(o,cep.replace(/\D/g,''))}/>{o.name} · {money(o.price_cents)} · até {o.days} dias úteis</label>:<span>{o.name} · {money(o.price_cents)} · até {o.days} dias úteis</span>}</div>)}</div>}
export function ProductDetail({product:p}:{product:Product}){const[quantity,setQuantity]=useState(1),[photo,setPhoto]=useState(0);const{add,demo}=useCart();return <><div className="product-detail"><div><img className="gallery-main" src={p.images[photo]} alt={`${p.name} em ${p.color}`} fetchPriority="high" width={700} height={749}/><div className="gallery-thumbs">{p.images.map((src,i)=><button key={src} className={photo===i?'active':''} onClick={()=>setPhoto(i)} aria-label={`Ver foto ${i+1} de ${p.name}`} aria-pressed={photo===i}><img src={src} alt="" width={82} height={82} loading="lazy"/></button>)}</div></div><div className="product-details"><p className="eyebrow">{p.category==='gesso'?'Gesso artesanal':'Têxtil artesanal'}</p><h1>{p.name}</h1><p className="main-price">{money(p.price_cents)}</p><p className="small muted">{money(pixPrice(p.price_cents))} no Pix <span style={{color:'var(--primary)'}}>· 5% de desconto</span></p><p className="small muted">Cartão em até 12x, sujeito às condições do Mercado Pago.</p><p className="description">{p.description}</p><p className="small">Cor: <strong style={{fontWeight:400}}>{p.color}</strong></p><div className="purchase-row"><Quantity value={quantity} onChange={setQuantity} max={Math.min(p.stock,20)}/><button className="button" disabled={!p.stock} onClick={()=>add(p.id,quantity)}>{p.stock?'Adicionar à sacola':'Indisponível'}<ArrowRight/></button></div>{demo&&<p className="small muted">Peça demonstrativa · imagem ilustrativa.</p>}<ShippingCalculator items={[{id:p.id,quantity}]}/><div className="details-list"><details open><summary>Dimensões e detalhes</summary><p>{p.dimensions}. O trabalho artesanal pode apresentar pequenas variações de textura, forma e cor.</p></details><details><summary>Como cuidar da sua peça</summary><p>{p.care}</p></details></div></div></div></>}
