'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {ShoppingBag,Menu,MessageCircle,ArrowUpRight,Camera,ArrowRight} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {useCart} from './provider';
export function Wordmark(){return <span className="wordmark"><span>CASA</span><strong>AURA</strong><small>DESIGN COM ESSÊNCIA</small></span>}
export function Header(){const {count}=useCart();const[open,setOpen]=useState(false);return <><a className="skip" href="#conteudo">Pular para o conteúdo</a><div className="topbar">GESSO & TÊXTIL ARTESANAL <span aria-hidden="true">&nbsp; · &nbsp;</span> FEITO PARA PERMANECER</div><header className="header"><div className="container header-inner"><nav className="nav" aria-label="Navegação principal"><Link href="/loja">Todas as peças</Link><Link href="/loja?categoria=gesso">Gesso</Link><Link href="/loja?categoria=textil">Têxtil</Link></nav><div className="mobile-menu"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger aria-label="Abrir menu"><Menu size={24}/></SheetTrigger><SheetContent side="left"><SheetHeader><SheetTitle>Casa Aura</SheetTitle><SheetDescription>Encontre peças para o seu espaço.</SheetDescription></SheetHeader><nav className="mobile-links"><Link href="/" onClick={()=>setOpen(false)}>Início</Link><Link href="/loja" onClick={()=>setOpen(false)}>Todas as peças</Link><Link href="/loja?categoria=gesso" onClick={()=>setOpen(false)}>Gesso</Link><Link href="/loja?categoria=textil" onClick={()=>setOpen(false)}>Têxtil artesanal</Link></nav></SheetContent></Sheet></div><Link href="/" aria-label="Casa Aura — página inicial"><Wordmark/></Link><div className="header-actions"><a className="social-label" href="https://www.instagram.com/casa.aura.decor/" target="_blank" rel="noopener noreferrer">Nosso universo <ArrowUpRight size={13} style={{display:'inline'}}/></a><Link href="/carrinho" className="bag" aria-label={`Sacola com ${count} peças`}><ShoppingBag size={21} strokeWidth={1.4}/><span className="bag-count">{count}</span></Link></div></div></header></>}
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-top"><div className="footer-brand"><Link href="/" aria-label="Casa Aura, início"><Wordmark/></Link><p>Objetos que acolhem.<br/>Detalhes que contam histórias.</p></div><div><h3>Explore</h3><nav className="footer-links"><Link href="/loja">Todas as peças</Link><Link href="/loja?categoria=gesso">Coleção Gesso</Link><Link href="/loja?categoria=textil">Têxtil artesanal</Link></nav></div><div><h3>Vamos conversar</h3><div className="footer-links"><a href="https://www.instagram.com/casa.aura.decor/" target="_blank" rel="noopener noreferrer" style={{display:'flex',gap:8,alignItems:'center'}}><Camera size={16}/> @casa.aura.decor</a><Link href="/privacidade">Política de privacidade</Link><button className="footer-policy" onClick={()=>window.dispatchEvent(new Event('aura-cookie-settings'))}>Preferências de cookies</button></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Casa Aura. Todos os direitos reservados.</span><span>Gesso & têxtil artesanal · Estética atemporal</span><Link href="/admin">Área da marca</Link></div></div></footer>}
export function CookieBanner(){const[show,setShow]=useState(false);useEffect(()=>{try{setShow(!localStorage.getItem('aura-consent-v1'))}catch{setShow(true)}const open=()=>setShow(true);window.addEventListener('aura-cookie-settings',open);return()=>window.removeEventListener('aura-cookie-settings',open)},[]);function choose(value:string){try{localStorage.setItem('aura-consent-v1',JSON.stringify({choice:value,at:new Date().toISOString(),version:1}))}catch{}setShow(false)}if(!show)return null;return <aside className="cookie-banner" aria-label="Preferências de cookies"><h3>Seu espaço, suas escolhas.</h3><p>Usamos armazenamento essencial para a sacola. Você decide sobre cookies opcionais, atualmente inativos. <Link href="/privacidade" style={{textDecoration:'underline'}}>Saiba mais</Link>.</p><div className="cookie-buttons"><button className="button button-outline" onClick={()=>choose('essential')}>Somente essenciais</button><button className="button" onClick={()=>choose('accepted')}>Aceitar opcionais</button></div></aside>}
export function WhatsApp({number}:{number:string}){const [message,setMessage]=useState('Olá, Casa Aura! Gostaria de saber mais sobre as peças.');const valid=/^55\d{10,11}$/.test(number);return <Dialog><DialogTrigger className="floating-chat" aria-label="Conversar com Casa Aura pelo WhatsApp"><MessageCircle/><span>Podemos ajudar?</span></DialogTrigger><DialogContent className="chat-content"><DialogHeader><DialogTitle className="serif" style={{fontSize:28}}>Um toque de cuidado.</DialogTitle><DialogDescription>Atendimento Casa Aura</DialogDescription></DialogHeader><p className="chat-message">Olá! Que bom ter você por aqui. Como podemos ajudar a deixar o seu espaço com mais essência?</p>{valid?<><label className="form-label"><span>Sua mensagem</span><textarea className="field" rows={3} maxLength={800} value={message} onChange={e=>setMessage(e.target.value)}/></label><a className="button" href={`https://wa.me/${number}?text=${encodeURIComponent(message)}`} target="_blank" rel="noopener noreferrer">Continuar no WhatsApp <ArrowRight size={16}/></a></>:<><p>Nosso WhatsApp estará disponível em breve. Por enquanto, fale com a Casa Aura pelo Instagram.</p><a className="button" href="https://www.instagram.com/casa.aura.decor/" target="_blank" rel="noopener noreferrer">Abrir Instagram <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog>}
